### ISSUE TITLE
Auth feature

### ISSUE THREAD

**Issue by pwFoo** [jeroenpeeters/docker-ssh#13]
Would be important to secure the login with pubkey or just user / password.
Feature is planned, but should be high priority.

**Comment by jeroenpeeters** [comment]
I've added a simple authentication mechanism that allows authentication of a single user only. More complex authentication strategies will be implemented soon.

**Comment by jeroenpeeters** [comment]
users can now also be authenticated against a list of user:password pairs.

**Comment by bdelbasso** [comment]
Hello, I've proposed an implementation of the pubkey auth in this [PR](https://github.com/jeroenpeeters/docker-ssh/pull/16).

**Comment by jeroenpeeters** [comment]
All proposed authentication mechanisms have been implemented since version 4.0.0
