### ISSUE TITLE
Does not work on Docker for Windows

### ISSUE THREAD

**Issue by h-e-n-r-y** [jeroenpeeters/docker-ssh#20]
Unfortunately there ist no /var/run/docker.sock on Windows.
Can I use docker-ssh on Docker for Windows without mounting this as a volume?

Henry

**Comment by jeroenpeeters** [comment]
I actually don't know. I don't use Windows myself nor do I have the opportunity to test this. As far as I know Docker on Windows is running inside a VirtualBox Linux VM. So in theory it should be possible to make it work. Please let me know when you make any progress on this. That being said, I highly recommend to use Linux directly.

**Comment by thaeli** [comment]
I have it working just fine from docker-compose on Docker for Windows (Docker 1.13.0) with the following config:

```web_ssh:
  image: jeroenpeeters/docker-ssh
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
  ports:
    - "2222:22"
    - "8022:8022"
  environment:
    - CONTAINER=container_name_here
    - AUTH_MECHANISM=simpleAuth
    - AUTH_USER=ssh
    - AUTH_PASSWORD=ssh
```

**Comment by h-e-n-r-y** [comment]
After finding a typo I can confirm now, that it runs seemlessly unter
docker for windows.

Henry


Jeroen Peeters <notifications@github.com> schrieb am Do., 24. Nov. 2016 um
18:57 Uhr:

**Comment by h-e-n-r-y** [comment]
Also I had to use Powershell on Windows to issue the docker run command,
because git-bash does weird escaping of slashes. so the volume mounting did
not work correctly.

Henry

Jeroen Peeters <notifications@github.com> schrieb am Do., 24. Nov. 2016 um
18:57 Uhr:
