### ISSUE TITLE
[Typo] Change AUTHORIZED KEYS quotes

### ISSUE THREAD

**Issue by rrreche** [jeroenpeeters/docker-ssh#23]
Hello,

I am new to GitHub, excuse me if this is somehow the wrong way to approach this.

I think I found a typo in your howto's, regarding public key auth.

$ docker run -d -p 2222:22 \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v ./authorized_keys:/authorized_keys
  -e CONTAINER=my-container -e AUTH_MECHANISM=publicKey \
  -e AUTHORIZED_KEYS="/authorized_keys" \
  jeroenpeeters/docker-ssh

This did not work until I changed the line

-e AUTHORIZED_KEYS="/authorized_keys"

to

-e AUTHORIZED_KEYS=/authorized_keys

Which is: remove the quotes to make it work. If I did it like in the first line, I would get an ENOENT error - no file or directory found.

Thank you for your project!

Kind regards.

**Comment by jeroenpeeters** [comment]
Thanks, fixed.
