### ISSUE TITLE
remote command

### ISSUE THREAD

**Issue by charleschen** [jeroenpeeters/docker-ssh#3]
I'm trying to use a docker container as a jenkins slave, which pertains to the jenkins master connecting to the jenkins slave through ssh.  I thought the method would be perfect for my use case, however i can't issue a remote command:

```
$ ssh -p 2222 sfo java -jar ~/slave.jar
'java -jar ~/slave.jar' is not (yet) supported by Docker-SSH
```

are there any support of remote commands coming up?

**Comment by jeroenpeeters** [comment]
Issuing a single command is currently not yet supported indeed. Currently only ssh'ing to an interactive shell is implemented. More will follow soon, or you can implement it and send me a pull-request.

I can however recommend this image (https://hub.docker.com/r/evarga/jenkins-slave/) to use as  Jenkins slave. I'm using this one myself as well.

**Comment by jeroenpeeters** [comment]
Executing a single remote command is now supported.
