### ISSUE TITLE
need more help getting started

### ISSUE THREAD

**Issue by uptimestar** [jeroenpeeters/docker-ssh#35]
Hi, sadly I need more documentation to get started.
I get Received disconnect from ::1 port 2222:2: 

Is there a sample container to connect to? It wont connect to mine.
Maybe even a shell script that wraps the command.

**Comment by jeroenpeeters** [comment]
```
docker run -d --name my-nginx nginx
docker run -d -p 2222:22 \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -e FILTERS={\"name\":[\"^/my-nginx$\"]} -e AUTH_MECHANISM=noAuth \
  jeroenpeeters/docker-ssh
```

and then connect to the ssh service running on port `2222`

`ssh -p 2222 localhost`

**Comment by uptimestar** [comment]
I did just that:
Received disconnect from ::1 port 2222:2: 
Disconnected from ::1 port 2222

**Comment by jeroenpeeters** [comment]
Can you look around for more debug information? I can just run the snippet above without any problems. At this point I don't know how to assist.
