### ISSUE TITLE
id_rsa is a private key...

### ISSUE THREAD

**Issue by sk8forether** [jeroenpeeters/docker-ssh#42]
Perhaps you didn't mean to include this?

**Comment by bbarker** [comment]
better yet there's a public key included

**Comment by jrddunbr** [comment]
Drat! This is what happens when you hesitate on making an issue; I made a duplicate :/ https://github.com/jeroenpeeters/docker-ssh/issues/43

**Comment by jeroenpeeters** [comment]
Duplicate of #43
