### ISSUE TITLE
Is there a Fork which has evolved further?

### ISSUE THREAD

**Issue by back-2-95** [jeroenpeeters/docker-ssh#55]
There are currently quite many forks: https://github.com/jeroenpeeters/docker-ssh/network/members

Maybe some of them have progressed further and added functionality & squashed bugs?

They could be listed here as it's clear this repo is not active anymore.

**Comment by frugan-dev** [comment]
Hi there,

here http://gitpop2.herokuapp.com/jeroenpeeters/docker-ssh you can see all forks and sort them by date, stars, etc.
but I don't think there is much activity...
